import Config

# Database
config :emakola, Emakola.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "emakola_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# Use local filesystem storage in dev (no S3 needed)
config :emakola, :storage, Emakola.Storage.Local

# AshAuthentication token signing secret — dev-only value
config :emakola,
  token_signing_secret: "dev-only-not-for-production-at-least-32-bytes!!"

# Social login (OAuth) — set provider creds via env to test locally; unset = off
# (ship-dark, see EmakolaWeb.OAuth). Google permits http://localhost redirect
# URIs for dev; Facebook/Apple need the deployed host or a tunnel.
config :emakola, :oauth,
  google: %{
    client_id: System.get_env("GOOGLE_CLIENT_ID"),
    client_secret: System.get_env("GOOGLE_CLIENT_SECRET")
  },
  facebook: %{
    client_id: System.get_env("FACEBOOK_CLIENT_ID"),
    client_secret: System.get_env("FACEBOOK_CLIENT_SECRET")
  },
  apple: %{
    client_id: System.get_env("APPLE_CLIENT_ID"),
    team_id: System.get_env("APPLE_TEAM_ID"),
    private_key_id: System.get_env("APPLE_KEY_ID"),
    private_key_path: System.get_env("APPLE_PRIVATE_KEY_PATH")
  }

config :emakola, :oauth_redirect_base, "http://localhost:4000/oauth"

# Phone (WhatsApp/SMS) OTP auth enabled in dev (codes go to the Log providers).
config :emakola, :phone_auth_enabled, true

# Payment gateway credentials — harmless placeholders for dev (env vars
# override). Prod credentials are set in runtime.exs.
config :emakola, Emakola.Payments.PaystackClient,
  secret_key: System.get_env("PAYSTACK_SECRET_KEY", "sk_test_placeholder"),
  public_key: System.get_env("PAYSTACK_PUBLIC_KEY", "pk_test_placeholder")

config :emakola, Emakola.Payments.HubtelClient,
  client_id: System.get_env("HUBTEL_CLIENT_ID"),
  client_secret: System.get_env("HUBTEL_CLIENT_SECRET")

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :emakola, EmakolaWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  # PORT env override lets a second checkout/worktree run alongside the default server
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "BTgCVIeHS6oYm8sR2iE60Ok0MSsYhlE80chog5RPe82cm5V2NRD6i6mbY4pjMgtX",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:emakola, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:emakola, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :emakola, EmakolaWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/emakola_web/router\.ex$"E,
      ~r"lib/emakola_web/(controllers|live|components)/.*\.(ex|heex)$"E,
      # Theme files (storefront templates)
      ~r"lib/emakola/themes/.*\.ex$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :emakola, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
