defmodule Emakola.Repo.Migrations.AddStorePayoutAccount do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:store_payout_accounts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :store_id,
          references(:stores,
            column: :id,
            name: "store_payout_accounts_store_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :payout_provider, :text, null: false, default: "paystack"
      add :subaccount_code, :text
      add :payout_destination, :map
      add :verification_status, :text, null: false, default: "unverified"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:store_payout_accounts, [:store_id],
             name: "store_payout_accounts_unique_store_payout_index"
           )
  end

  def down do
    drop constraint(:store_payout_accounts, "store_payout_accounts_store_id_fkey")

    drop_if_exists unique_index(:store_payout_accounts, [:store_id],
                     name: "store_payout_accounts_unique_store_payout_index"
                   )

    drop table(:store_payout_accounts)
  end
end
