defmodule Emakola.Repo.Migrations.AddProtectionHolds do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:protection_holds, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :store_id, :uuid, null: false
      add :payment_id, :uuid, null: false
      add :order_id, :uuid, null: false
      add :amount, :bigint, null: false
      add :fee, :bigint, null: false
      add :net, :bigint, null: false
      add :status, :text, null: false, default: "held"
      add :frozen_at, :utc_datetime_usec
      add :release_after, :utc_datetime_usec
      add :released_at, :utc_datetime_usec
      add :release_reason, :text
      add :complaint_reason, :text
      add :complaint_text, :text
      add :resolution, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:protection_holds, [:store_id, :status, :release_after])

    create unique_index(:protection_holds, [:store_id, :payment_id],
             name: "protection_holds_unique_payment_index"
           )

    alter table(:payments) do
      add :payable_amount, :bigint
    end
  end

  def down do
    alter table(:payments) do
      remove :payable_amount
    end

    drop_if_exists unique_index(:protection_holds, [:store_id, :payment_id],
                     name: "protection_holds_unique_payment_index"
                   )

    drop_if_exists index(:protection_holds, [:store_id, :status, :release_after])

    drop table(:protection_holds)
  end
end
