defmodule Emakola.Repo.Migrations.AddDirectoryStanding do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:store_directory_standings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :eligible, :boolean, null: false, default: false
      add :disqualifiers, {:array, :text}, null: false, default: []
      add :score, :bigint, null: false, default: 0
      add :score_breakdown, :map, null: false, default: %{}
      add :slot, :text
      add :computed_at, :utc_datetime_usec
      add :override_slot, :text
      add :override_excluded, :boolean, null: false, default: false
      add :override_reason, :text
      add :override_until, :utc_datetime_usec
      add :override_by_id, :uuid
      add :override_at, :utc_datetime_usec
      add :paid_placement_weight, :bigint, null: false, default: 0
      add :paid_placement_until, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :store_id,
          references(:stores,
            column: :id,
            name: "store_directory_standings_store_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:store_directory_standings, [:store_id],
             name: "store_directory_standings_unique_store_index"
           )

    alter table(:stores) do
      add :directory_eligible, :boolean, null: false, default: true
      add :directory_score, :bigint
      add :directory_slot, :text
    end
  end

  def down do
    alter table(:stores) do
      remove :directory_slot
      remove :directory_score
      remove :directory_eligible
    end

    drop constraint(:store_directory_standings, "store_directory_standings_store_id_fkey")

    drop_if_exists unique_index(:store_directory_standings, [:store_id],
                     name: "store_directory_standings_unique_store_index"
                   )

    drop table(:store_directory_standings)
  end
end
