defmodule Emakola.Repo.Migrations.AddPlatformAuditLogs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:platform_audit_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :actor_id, :uuid
      add :action, :text, null: false
      add :metadata, :map, default: %{}
      add :ip, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:platform_audit_logs, [:inserted_at, :id])
  end

  def down do
    drop_if_exists index(:platform_audit_logs, [:inserted_at, :id])

    drop table(:platform_audit_logs)
  end
end
