defmodule Emakola.Repo.Migrations.AddPaymentSplits do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:payments) do
      add :split_mode, :text, null: false, default: "none"
      add :split_code, :text
    end

    create table(:payment_splits, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :store_id, :uuid, null: false

      add :payment_id,
          references(:payments,
            column: :id,
            name: "payment_splits_payment_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :role, :text, null: false
      add :recipient_store_id, :uuid
      add :supplier_id, :uuid
      add :subaccount_code, :text
      add :amount, :bigint, null: false
      add :status, :text, null: false, default: "pending"
      add :paystack_split_reference, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:payment_splits, "payment_splits_payment_id_fkey")

    drop table(:payment_splits)

    alter table(:payments) do
      remove :split_code
      remove :split_mode
    end
  end
end
