defmodule Emakola.Repo.Migrations.MakeLineItemVariantOptional do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`,
  then trimmed to only the `line_items` hunk: scoping generation to the
  Orders domain still bundled unrelated snapshot drift for `orders`,
  `fulfillments`, and `fulfillment_delivery_proofs` (columns/tables already
  live in the database from prior migrations — the repo has never had
  `priv/resource_snapshots` fully tracked, see prior migrations tagged
  "Hand-written: `mix ash.codegen` is unusable in this repo"). Discarding
  those foreign snapshots/hunks follows the existing recovery pattern.
  """

  use Ecto.Migration

  def up do
    alter table(:line_items) do
      modify :variant_id, :uuid, null: true
    end
  end

  def down do
    alter table(:line_items) do
      modify :variant_id, :uuid, null: false
    end
  end
end
