defmodule Emakola.Repo.Migrations.CreateVariantOptionValues do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:variants, [:store_id, :sku],
                     name: "variants_unique_store_sku_index"
                   )

    create unique_index(:variants, [:store_id, :sku], name: "variants_unique_store_sku_index")

    create table(:variant_option_values, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :store_id,
          references(:stores,
            column: :id,
            name: "variant_option_values_store_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :variant_id,
          references(:variants,
            column: :id,
            name: "variant_option_values_variant_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :option_value_id,
          references(:option_values,
            column: :id,
            name: "variant_option_values_option_value_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:variant_option_values, [:variant_id, :option_value_id],
             name: "variant_option_values_unique_variant_option_value_index"
           )
  end

  def down do
    drop_if_exists unique_index(:variant_option_values, [:variant_id, :option_value_id],
                     name: "variant_option_values_unique_variant_option_value_index"
                   )

    drop constraint(:variant_option_values, "variant_option_values_store_id_fkey")

    drop constraint(:variant_option_values, "variant_option_values_variant_id_fkey")

    drop constraint(:variant_option_values, "variant_option_values_option_value_id_fkey")

    drop table(:variant_option_values)

    drop_if_exists unique_index(:variants, [:store_id, :sku],
                     name: "variants_unique_store_sku_index"
                   )

    create unique_index(:variants, [:store_id, :sku],
             name: "variants_unique_store_sku_index",
             nulls_distinct: false
           )
  end
end
