defmodule Emakola.Repo.Migrations.CreateOptionsAndVariants do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:variants, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :product_id,
          references(:products,
            column: :id,
            name: "variants_product_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :store_id,
          references(:stores,
            column: :id,
            name: "variants_store_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :sku, :text
      add :price, :bigint, null: false
      add :compare_at_price, :bigint
      add :stock_quantity, :bigint, null: false, default: 0
      add :track_inventory, :boolean, null: false, default: true
      add :weight_grams, :bigint
      add :barcode, :text
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:variants, [:store_id, :sku], name: "variants_unique_store_sku_index")

    create table(:option_values, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :store_id,
          references(:stores,
            column: :id,
            name: "option_values_store_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :option_type_id, :uuid, null: false
      add :value, :text, null: false
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:option_types, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:option_values) do
      modify :option_type_id,
             references(:option_types,
               column: :id,
               name: "option_values_option_type_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:option_values, [:option_type_id, :value],
             name: "option_values_unique_type_value_index"
           )

    alter table(:option_types) do
      add :store_id,
          references(:stores,
            column: :id,
            name: "option_types_store_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :product_id,
          references(:products,
            column: :id,
            name: "option_types_product_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :name, :text, null: false
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:option_types, [:product_id, :name],
             name: "option_types_unique_product_name_index"
           )

    execute("""
    ALTER TABLE variants ADD CONSTRAINT stock_non_negative CHECK (stock_quantity >= 0)
    """)
  end

  def down do
    execute("""
    ALTER TABLE variants DROP CONSTRAINT IF EXISTS stock_non_negative
    """)

    drop_if_exists unique_index(:option_types, [:product_id, :name],
                     name: "option_types_unique_product_name_index"
                   )

    drop constraint(:option_types, "option_types_store_id_fkey")

    drop constraint(:option_types, "option_types_product_id_fkey")

    alter table(:option_types) do
      remove :updated_at
      remove :inserted_at
      remove :position
      remove :name
      remove :product_id
      remove :store_id
    end

    drop_if_exists unique_index(:option_values, [:option_type_id, :value],
                     name: "option_values_unique_type_value_index"
                   )

    drop constraint(:option_values, "option_values_option_type_id_fkey")

    alter table(:option_values) do
      modify :option_type_id, :uuid
    end

    drop table(:option_types)

    drop constraint(:option_values, "option_values_store_id_fkey")

    drop table(:option_values)

    drop_if_exists unique_index(:variants, [:store_id, :sku],
                     name: "variants_unique_store_sku_index"
                   )

    drop constraint(:variants, "variants_product_id_fkey")

    drop constraint(:variants, "variants_store_id_fkey")

    drop table(:variants)
  end
end
