defmodule Emakola.Repo.Migrations.CreateStoreDomains do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:store_domains, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :store_id,
          references(:stores,
            column: :id,
            name: "store_domains_store_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :host, :text, null: false
      add :type, :text, null: false, default: "subdomain"
      add :status, :text, null: false, default: "active"
      add :serve_in_place?, :boolean, null: false, default: false
      add :primary?, :boolean, null: false, default: false
      add :verified_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:store_domains, [:host], name: "store_domains_unique_host_index")
  end

  def down do
    drop constraint(:store_domains, "store_domains_store_id_fkey")

    drop_if_exists unique_index(:store_domains, [:host], name: "store_domains_unique_host_index")

    drop table(:store_domains)
  end
end
