defmodule Emakola.Repo.Migrations.AddReturnRefundDispatchFee do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`,
  then trimmed to only the `returns` hunk: `mix ash.codegen` bundled
  unrelated snapshot drift for dozens of other resources (the repo has never
  had `priv/resource_snapshots` fully tracked — see prior migrations tagged
  "Hand-written: `mix ash.codegen` is unusable in this repo"). Discarding
  those foreign snapshots/hunks follows the existing recovery pattern.
  """

  use Ecto.Migration

  def up do
    alter table(:returns) do
      add :refund_dispatch_fee?, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:returns) do
      remove :refund_dispatch_fee?
    end
  end
end
