defmodule Emakola.Repo.Migrations.AddStoreSettingsColumns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:stores) do
      add :description, :text
      add :logo_url, :text
      add :contact_email, :text
      add :contact_phone, :text
      add :address, :text
      add :city, :text
      add :region, :text
      add :whatsapp_number, :text
      add :active, :boolean, default: true
    end

    create table(:delivery_zones, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :store_id,
          references(:stores,
            column: :id,
            name: "delivery_zones_store_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :name, :text, null: false
      add :fee, :bigint, null: false
      add :estimated_days, :bigint, default: 1
      add :active, :boolean, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:delivery_zones, [:store_id, :name],
             name: "delivery_zones_unique_store_name_index"
           )
  end

  def down do
    drop_if_exists unique_index(:delivery_zones, [:store_id, :name],
                     name: "delivery_zones_unique_store_name_index"
                   )

    drop constraint(:delivery_zones, "delivery_zones_store_id_fkey")

    drop table(:delivery_zones)

    alter table(:stores) do
      remove :active
      remove :whatsapp_number
      remove :region
      remove :city
      remove :address
      remove :contact_phone
      remove :contact_email
      remove :logo_url
      remove :description
    end
  end
end
