defmodule Emakola.Repo.Migrations.AddSupplierLinkedStore do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:suppliers) do
      add :linked_store_id,
          references(:stores,
            column: :id,
            name: "suppliers_linked_store_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:suppliers, "suppliers_linked_store_id_fkey")

    alter table(:suppliers) do
      remove :linked_store_id
    end
  end
end
