defmodule Emakola.Repo.Migrations.AddSnapVerifiedToProducts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:products) do
      add :snap_verified, :boolean,
        default: false,
        null: false
    end
  end

  def down do
    alter table(:products) do
      remove :snap_verified
    end
  end
end
