defmodule Emakola.Repo.Migrations.AddUserSessions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_sessions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :ip, :text
      add :user_agent, :text
      add :last_seen_at, :utc_datetime_usec, null: false
      add :revoked_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "user_sessions_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:user_sessions, [:user_id])
  end

  def down do
    drop_if_exists index(:user_sessions, [:user_id])

    drop constraint(:user_sessions, "user_sessions_user_id_fkey")

    drop table(:user_sessions)
  end
end
