defmodule Emakola.Repo.Migrations.AddDeviceTokenMerchantIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:device_tokens, [:store_id, :merchant_id])
  end

  def down do
    drop_if_exists index(:device_tokens, [:store_id, :merchant_id])
  end
end
