defmodule Emakola.Repo.Migrations.AddStoreFeaturedAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:stores) do
      add :featured_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:stores) do
      remove :featured_at
    end
  end
end
