defmodule Emakola.Repo.Migrations.AddSusuPlans do
  @moduledoc """
  Creates `susu_plans` + `orders.susu_plan_id`.

  This file was autogenerated with `mix ash_postgres.generate_migrations
  --domains Emakola.Orders`, then trimmed to only these two hunks:
  scoping generation to the Orders domain still bundled unrelated snapshot
  drift for `fulfillments.dispatch_fee` and `fulfillment_delivery_proofs`
  (columns/tables already live in the database from prior migrations — this
  repo has never had `priv/resource_snapshots` fully tracked, see prior
  migrations tagged "Hand-written: `mix ash.codegen` is unusable in this
  repo"). Discarding those foreign hunks follows the existing recovery
  pattern (see `20260730123601_add_pay_links.exs`). The generator also
  proposed DROP TABLE migrations for ~60 untracked resources and stamped
  `"drop_table_opted_out": true` onto their snapshots as a side effect —
  those snapshot edits were reverted; nothing here touches those tables.

  `susu_plans_unique_code_index` covers `code` alone (not `(store_id,
  code)`, ash_postgres's default for attribute-multitenant identities). A
  buyer opens `/susu/:code` with no store context, so the code must be
  unique across every tenant, not just within one — see the
  `all_tenants?: true` identity on `Emakola.Orders.SusuPlan`.
  """

  use Ecto.Migration

  def up do
    create table(:susu_plans, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :store_id, :uuid, null: false
      add :code, :text, null: false
      add :type, :text, null: false
      add :variant_id, :uuid
      add :quantity, :bigint, null: false, default: 1
      add :title, :text
      add :total_amount, :bigint, null: false
      add :min_chunk, :bigint, null: false, default: 1000
      add :deadline, :utc_datetime_usec, null: false
      add :fee_rate_bps, :bigint, null: false
      add :collect_delivery, :boolean, null: false, default: true
      add :status, :text, null: false, default: "pending"
      add :customer_id, :uuid
      add :contributed_amount, :bigint, null: false, default: 0
      add :delivery_address, :map
      add :stock_reserved, :boolean, null: false, default: false
      add :last_nudged_at, :utc_datetime_usec
      add :warned_7d_at, :utc_datetime_usec
      add :warned_1d_at, :utc_datetime_usec
      add :note, :text
      add :created_by_user_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:susu_plans, [:code], name: "susu_plans_unique_code_index")

    alter table(:orders) do
      add :susu_plan_id, :uuid
    end
  end

  def down do
    alter table(:orders) do
      remove :susu_plan_id
    end

    drop_if_exists unique_index(:susu_plans, [:code], name: "susu_plans_unique_code_index")

    drop table(:susu_plans)
  end
end
