defmodule Emakola.Repo.Migrations.AddDeviceTokens do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:device_tokens, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :store_id, :uuid, null: false
      add :platform, :text, null: false
      add :token, :text, null: false
      add :last_seen_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :merchant_id,
          references(:merchants,
            column: :id,
            name: "device_tokens_merchant_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:device_tokens, [:token], name: "device_tokens_unique_token_index")
    create index(:device_tokens, [:store_id])
  end

  def down do
    drop constraint(:device_tokens, "device_tokens_merchant_id_fkey")

    drop_if_exists unique_index(:device_tokens, [:token],
                     name: "device_tokens_unique_token_index"
                   )

    drop table(:device_tokens)
  end
end
