defmodule Emakola.Repo.Migrations.FixProtectionHoldsSweepIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`

  Replaces the `(store_id, status, release_after)` index with
  `(status, release_after)` — the hourly cron sweep
  (`Emakola.Payments.Workers.ProtectionSweepWorker`) queries across every
  tenant, so a tenant-prefixed index can never be used for it. Trimmed of an
  unrelated `payouts.store_id` FK/index drift the domain-wide diff
  surfaced (same pre-existing gap noted in the migration that created this
  table — left untouched here too).
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:protection_holds, [:store_id, :status, :release_after])

    create index(:protection_holds, [:status, :release_after])
  end

  def down do
    drop_if_exists index(:protection_holds, [:status, :release_after])

    create index(:protection_holds, [:store_id, :status, :release_after])
  end
end
