defmodule Emakola.Repo.Migrations.CreateOrders do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:payments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :store_id,
          references(:stores,
            column: :id,
            name: "payments_store_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :order_id, :uuid
      add :amount, :bigint, null: false
      add :currency, :text, null: false, default: "GHS"
      add :status, :text, null: false, default: "pending"
      add :gateway, :text, null: false
      add :gateway_reference, :text
      add :gateway_response, :map
      add :customer_email, :text
      add :metadata, :map, default: %{}
      add :refunded_amount, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:orders, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:payments) do
      modify :order_id,
             references(:orders,
               column: :id,
               name: "payments_order_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:payments, [:gateway_reference],
             name: "payments_unique_gateway_reference_index"
           )

    alter table(:orders) do
      add :store_id,
          references(:stores,
            column: :id,
            name: "orders_store_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :customer_id, :uuid
      add :order_number, :text, null: false
      add :status, :text, null: false, default: "pending"
      add :subtotal, :bigint, null: false, default: 0
      add :total, :bigint, null: false, default: 0
      add :currency, :text, null: false, default: "GHS"
      add :notes, :text
      add :shipping_address, :map
      add :billing_address, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:line_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :order_id,
          references(:orders,
            column: :id,
            name: "line_items_order_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :store_id, :uuid, null: false

      add :variant_id,
          references(:variants,
            column: :id,
            name: "line_items_variant_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :product_title, :text, null: false
      add :variant_sku, :text
      add :unit_price, :bigint, null: false
      add :quantity, :bigint, null: false
      add :line_total, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:customers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:orders) do
      modify :customer_id,
             references(:customers,
               column: :id,
               name: "orders_customer_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:orders, [:store_id, :order_number],
             name: "orders_unique_store_order_number_index"
           )

    alter table(:customers) do
      add :store_id,
          references(:stores,
            column: :id,
            name: "customers_store_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :email, :citext, null: false
      add :name, :text
      add :phone, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:customers, [:store_id, :email],
             name: "customers_unique_store_email_index"
           )
  end

  def down do
    drop_if_exists unique_index(:customers, [:store_id, :email],
                     name: "customers_unique_store_email_index"
                   )

    drop constraint(:customers, "customers_store_id_fkey")

    alter table(:customers) do
      remove :updated_at
      remove :inserted_at
      remove :phone
      remove :name
      remove :email
      remove :store_id
    end

    drop_if_exists unique_index(:orders, [:store_id, :order_number],
                     name: "orders_unique_store_order_number_index"
                   )

    drop constraint(:orders, "orders_customer_id_fkey")

    alter table(:orders) do
      modify :customer_id, :uuid
    end

    drop table(:customers)

    drop constraint(:line_items, "line_items_order_id_fkey")

    drop constraint(:line_items, "line_items_variant_id_fkey")

    drop table(:line_items)

    drop constraint(:orders, "orders_store_id_fkey")

    alter table(:orders) do
      remove :updated_at
      remove :inserted_at
      remove :billing_address
      remove :shipping_address
      remove :notes
      remove :currency
      remove :total
      remove :subtotal
      remove :status
      remove :order_number
      remove :customer_id
      remove :store_id
    end

    drop_if_exists unique_index(:payments, [:gateway_reference],
                     name: "payments_unique_gateway_reference_index"
                   )

    drop constraint(:payments, "payments_order_id_fkey")

    alter table(:payments) do
      modify :order_id, :uuid
    end

    drop table(:orders)

    drop constraint(:payments, "payments_store_id_fkey")

    drop table(:payments)
  end
end
