defmodule Emakola.Repo.Migrations.CreateImages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:images, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :store_id,
          references(:stores,
            column: :id,
            name: "images_store_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :product_id,
          references(:products,
            column: :id,
            name: "images_product_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :variant_id, :uuid
      add :url, :text, null: false
      add :thumbnail_url, :text
      add :medium_url, :text
      add :alt_text, :text
      add :position, :bigint, default: 0
      add :content_type, :text, null: false
      add :file_size_bytes, :bigint
      add :processing_status, :text, null: false, default: "pending"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:images, "images_store_id_fkey")

    drop constraint(:images, "images_product_id_fkey")

    drop table(:images)
  end
end
