defmodule Emakola.Repo.Migrations.AddSusuPlanIdToPayments do
  @moduledoc """
  Adds `payments.susu_plan_id` + a plain index, for TC-3 chunk payments
  parented to a `Emakola.Orders.SusuPlan` instead of an order.

  Autogenerated with `mix ash_postgres.generate_migrations --domains
  Emakola.Payments`, then trimmed to just this hunk — the generator also
  proposed unrelated `protection_holds`/`payouts` FK+index drift (columns
  already live in the database from earlier hand-written migrations, never
  captured in their snapshots) and DROP TABLE migrations for every
  resource-less legacy table, stamping `drop_table_opted_out` onto their
  snapshots as a side effect. Those snapshot edits were reverted and the
  foreign `payouts`/`protection_holds` snapshot files discarded — same
  recovery pattern as `20260730123601_add_pay_links.exs` and
  `20260731114148_add_susu_plans.exs`.

  No FK reference, mirroring `orders.susu_plan_id` (added in
  20260731114148_add_susu_plans.exs) — plain nullable column only.
  """

  use Ecto.Migration

  def up do
    alter table(:payments) do
      add :susu_plan_id, :uuid
    end

    create index(:payments, [:susu_plan_id])
  end

  def down do
    drop_if_exists index(:payments, [:susu_plan_id])

    alter table(:payments) do
      remove :susu_plan_id
    end
  end
end
