defmodule Emakola.Repo.Migrations.AddPlatformInvites do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:platform_invites, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext, null: false
      add :permissions, {:array, :text}, null: false, default: []
      add :token_hash, :text, null: false
      add :invited_by_id, :uuid, null: false
      add :expires_at, :utc_datetime_usec, null: false
      add :accepted_at, :utc_datetime_usec
      add :revoked_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:platform_invites, [:token_hash],
             name: "platform_invites_unique_token_hash_index"
           )
  end

  def down do
    drop_if_exists unique_index(:platform_invites, [:token_hash],
                     name: "platform_invites_unique_token_hash_index"
                   )

    drop table(:platform_invites)
  end
end
