defmodule Emakola.Repo.Migrations.CreateCategories do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:stores, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :slug, :text, null: false
      add :currency, :text, null: false, default: "GHS"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:stores, [:slug], name: "stores_unique_slug_index")

    create table(:store_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false, default: "staff"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :merchant_id, :uuid, null: false
      add :store_id, :uuid, null: false
    end

    create table(:merchants, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:store_memberships) do
      modify :merchant_id,
             references(:merchants,
               column: :id,
               name: "store_memberships_merchant_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :store_id,
             references(:stores,
               column: :id,
               name: "store_memberships_store_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:store_memberships, [:merchant_id, :store_id],
             name: "store_memberships_unique_merchant_store_index"
           )

    alter table(:merchants) do
      add :email, :citext, null: false
      add :hashed_password, :text
      add :name, :text
      add :phone, :text
      add :business_name, :text
      add :avatar_url, :text
      add :preferences, :map, default: %{}
      add :confirmed_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:merchants, [:email], name: "merchants_unique_email_index")

    create table(:categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :store_id,
          references(:stores,
            column: :id,
            name: "categories_store_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :name, :text, null: false
      add :slug, :text, null: false
      add :description, :text

      add :parent_id,
          references(:categories,
            column: :id,
            name: "categories_parent_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:categories, [:store_id, :slug],
             name: "categories_unique_store_slug_index"
           )
  end

  def down do
    drop_if_exists unique_index(:categories, [:store_id, :slug],
                     name: "categories_unique_store_slug_index"
                   )

    drop constraint(:categories, "categories_store_id_fkey")

    drop constraint(:categories, "categories_parent_id_fkey")

    drop table(:categories)

    drop_if_exists unique_index(:merchants, [:email], name: "merchants_unique_email_index")

    alter table(:merchants) do
      remove :updated_at
      remove :inserted_at
      remove :confirmed_at
      remove :preferences
      remove :avatar_url
      remove :business_name
      remove :phone
      remove :name
      remove :hashed_password
      remove :email
    end

    drop_if_exists unique_index(:store_memberships, [:merchant_id, :store_id],
                     name: "store_memberships_unique_merchant_store_index"
                   )

    drop constraint(:store_memberships, "store_memberships_merchant_id_fkey")

    drop constraint(:store_memberships, "store_memberships_store_id_fkey")

    alter table(:store_memberships) do
      modify :store_id, :uuid
      modify :merchant_id, :uuid
    end

    drop table(:merchants)

    drop table(:store_memberships)

    drop_if_exists unique_index(:stores, [:slug], name: "stores_unique_slug_index")

    drop table(:stores)
  end
end
