defmodule Emakola.Repo.Migrations.CreateProducts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:products, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :store_id,
          references(:stores,
            column: :id,
            name: "products_store_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :category_id,
          references(:categories,
            column: :id,
            name: "products_category_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :title, :text, null: false
      add :slug, :text, null: false
      add :description, :text
      add :status, :text, null: false, default: "draft"
      add :seo_title, :text
      add :seo_description, :text
      add :tags, {:array, :text}, default: []
      add :published_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:products, [:store_id, :slug], name: "products_unique_store_slug_index")
  end

  def down do
    drop_if_exists unique_index(:products, [:store_id, :slug],
                     name: "products_unique_store_slug_index"
                   )

    drop constraint(:products, "products_store_id_fkey")

    drop constraint(:products, "products_category_id_fkey")

    drop table(:products)
  end
end
