defmodule Emakola.Repo.Migrations.AddPayLinks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`,
  then trimmed to only the `pay_links` + `orders.pay_link_id` hunks: scoping
  generation to the Orders domain still bundled unrelated snapshot drift for
  `orders.dispatch_fee_total`, `fulfillments.dispatch_fee`, and
  `fulfillment_delivery_proofs` (columns/tables already live in the database
  from prior migrations — the repo has never had `priv/resource_snapshots`
  fully tracked, see prior migrations tagged "Hand-written: `mix ash.codegen`
  is unusable in this repo"). Discarding those foreign snapshots/hunks
  follows the existing recovery pattern.

  The `pay_links_unique_code_index` is hand-amended to cover `code` alone
  (not `(store_id, code)`, ash_postgres's default for attribute-multitenant
  identities). A buyer opens `/pay/:code` with no store context, so the
  code must be unique across every tenant, not just within one — see the
  `all_tenants?: true` identity on `Emakola.Orders.PayLink`.
  """

  use Ecto.Migration

  def up do
    create table(:pay_links, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :store_id, :uuid, null: false
      add :code, :text, null: false
      add :type, :text, null: false
      add :variant_id, :uuid
      add :quantity, :bigint, null: false, default: 1
      add :title, :text
      add :amount, :bigint
      add :collect_delivery, :boolean, null: false, default: true
      add :status, :text, null: false, default: "active"
      add :expires_at, :utc_datetime_usec
      add :note, :text
      add :opened_count, :bigint, null: false, default: 0
      add :created_by_user_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:pay_links, [:code], name: "pay_links_unique_code_index")

    alter table(:orders) do
      add :pay_link_id, :uuid
    end
  end

  def down do
    alter table(:orders) do
      remove :pay_link_id
    end

    drop_if_exists unique_index(:pay_links, [:code], name: "pay_links_unique_code_index")

    drop table(:pay_links)
  end
end
